FROM nvcr.io/nvidia/tritonserver:24.01-py3

RUN apt-get update && apt-get install -y \
    python3-pip \
    git \
 && pip3 install --upgrade pip \
 && pip3 install --no-cache-dir torch transformers huggingface_hub accelerate vllm